export const StaticData = {
  Role: [
    {
      id: 1,
      name: "Manager",
      code: "Manager",
      isSendEmail: true,
      isCreateOrEditSheet: true,
      isCreateOrEditBook: true,
      isCreateOrEditStudent: true,
      createOrEditUser: true,
    },
    {
      id: 2,
      name: "Ban chủ nhiệm",
      code: "BCN",
      isSendEmail: true,
      isCreateOrEditSheet: true,
      isCreateOrEditBook: true,
      isCreateOrEditStudent: true,
    },
    { id: 3, name: "Thành viên", code: "TV" },
    {
      id: 4,
      name: "Nhập Liệu",
      code: "NL",
      isSendEmail: false,
      isCreateOrEditBook: true,
      isCreateOrEditStudent: true,
    },
    { id: 5, name: "Sự kiện", code: "SK" },
  ],

  Department: [
    { id: 1, name: "Ban chủ nhiệm", Code: "BCN" },
    { id: 2, name: "Phục vụ bạn đọc", Code: "PVBĐ" },
    { id: 3, name: "Tổ chức sự kiện", Code: "TCSK" },
    { id: 4, name: "Thông - Kỹ thuật", Code: "TT-KT" },
  ],
  Faculty: [
    { name: "Đang cập nhật" },
    { name: "Công nghệ thông tin" },
    { name: "Khoa học máy tính" },
    { name: "Điện tử viễn thông" },
    { name: "Công nghệ nông nghiệp" },
    { name: "Công nghệ hàng không vũ trụ" },
    { name: "Công nghệ xây dựng - giao thông" },
    { name: "Cơ kĩ thuật và tự động hóa" },
    { name: "Vật lý kĩ thuật & công nghệ Nano" },
  ],
  user: [
    {
      name: "admin",
      password: "123qwe",
      username: "admin",
      roleId: 1,
      departmentId: 1,
      email: "thuvienhsv.uet@gmail.com",
    },
  ],
};
